apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: registry
      port: {{ .Values.service.port }}
      targetPort: registry
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
