apiVersion: v2
name: rca-platform
description: RCA Platform application and local infrastructure
type: application
version: 0.1.2
appVersion: "0.1.2"
home: https://github.com/venumigihansa/NexCause
sources:
  - https://github.com/venumigihansa/NexCause
annotations:
  org.opencontainers.image.source: https://github.com/venumigihansa/NexCause
dependencies:
  - name: deployment-manager
    version: 0.1.2
    repository: file://charts/deployment-manager
  - name: rca-agent
    version: 0.1.2
    repository: file://charts/rca-agent
  - name: mcp-server
    version: 0.1.2
    repository: file://charts/mcp-server
  - name: postgres
    version: 0.1.2
    repository: file://charts/postgres
    condition: postgres.enabled
  - name: registry
    version: 0.1.2
    repository: file://charts/registry
    condition: registry.enabled
  - name: prometheus
    version: 29.17.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: observability.enabled
  - name: loki
    version: 7.0.0
    repository: https://grafana.github.io/helm-charts
    condition: observability.enabled
  - name: tempo
    version: 1.24.4
    repository: https://grafana.github.io/helm-charts
    condition: observability.enabled
  - name: opentelemetry-collector
    version: 0.165.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: observability.enabled
