replicaCount: 1
image:
  repository: ghcr.io/venumigihansa/nexcause-frontend
  tag: "0.1.3"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
config:
  environment: local
resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits: { cpu: 250m, memory: 128Mi }
podAnnotations: {}
containerSecurityContext:
  runAsUser: 101
  runAsGroup: 101
  readOnlyRootFilesystem: false
