grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 1h
    scrapeInterval: 30s
    evaluationInterval: 30s
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
    additionalScrapeConfigs:
      - job_name: otel-collector
        scrape_interval: 15s
        static_configs:
          - targets:
              - otel-collector-opentelemetry-collector.observability.svc.cluster.local:8889
