services:
  postgres:
    image: postgres:17
    container_name: deployment-manager-postgres
    environment:
      POSTGRES_USER: deployment_manager
      POSTGRES_PASSWORD: deployment_manager
      POSTGRES_DB: deployment_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
