{{- if .Values.global.externalSecrets.enabled }}
{{- range .Values.global.externalSecrets.mappings }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ $.Values.global.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.global.externalSecrets.secretStoreRef.kind }}
    name: {{ $.Values.global.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ .targetSecretName }}
    creationPolicy: Owner
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
