{{- if .Values.gateway.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "rca-platform.gatewayName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: {{ .Values.gateway.tls.secretName }}
  issuerRef:
    group: {{ .Values.gateway.tls.issuerRef.group }}
    kind: {{ .Values.gateway.tls.issuerRef.kind }}
    name: {{ .Values.gateway.tls.issuerRef.name }}
  dnsNames:
    - {{ .Values.gateway.consoleHostname | quote }}
    - {{ .Values.gateway.deploymentManagerHostname | quote }}
    - {{ .Values.gateway.applicationWildcardHostname | quote }}
{{- end }}
